---
- name: download and add the GPG key
  apt_key:
    url: "{{url}}"
    state: present

- name: add the JFrog Artifactory repository
  apt_repository:
    repo: "{{repo_url}}"
    state: present

- name: update cache
  apt:
    name: "{{package_name1}}"
    state: present
    update_cache: yes

- name: start and enable artifactory
  service:
    name: "{{service_name}}"
    state: started
    enabled: yes
  register: st

- name: status of artifactory
  debug:
      var: st
