---
- name: Java Configuration
  apt:
    name: "{{package_name}}"
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: java version
  command: "{{version}}"
  register: version

- name: print java-version
  debug:
    var: version

