---
- name: copy sonar.service
  copy:
    src: sonar.service
    dest: /etc/systemd/system/
    owner: jenkins
    group: jenkins
    mode: '666'

- name: deamon reload
  systemd:
    name: sonar
    daemon_reload: yes
    enabled: yes
- name: stop sonar
  service:
    name: sonar
    state: started
  register: status
- name: print status
  debug:
    var: status