---
- name: adding sonar.service file to systemd
  become: yes
  copy:
    src: sonar.service
    dest:  /etc/systemd/system/sonar.service
    owner: sonar
    group: sonar
- name: reoload systemd
  systemd:
    daemon_reload: yes
  notify: start and enable sonar service
