---
- name: copy sonar.service
  copy:
    src: sonar.service
    dest: /etc/systemd/system/
    owner: jenkins
    group: jenkins
    mode: '666'

- name: deamon reload
  systemd:
   daemon_reload: yes
   name: sonar
   state: started
   enabled: yes
  register: status
- name: print status
  debug:
    var: status