---
- name: installing unzip and jdk11
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - pkg1
    - pkg2
- name: java version
  command: "{{cmd}}"
  register: version
- name: check javaversion
  debug:
    var: version
...