---
- name: installing unzip and jdk11
  apt:
    name: "{{ item_name}}"
    state: present
  with_items:
    - pkg1
    - pkg2
  loop_control:
    loop_var: item_name

- name: java version
  command: "{{cmd}}"
  register: version
- name: check javaversion
  debug:
    var: version
...