---
# database configuration, creating user for db, creating db 
    - name: creating user
      become: true
      user:
        name: "{{user2}}"
        comment: "{{comment}}"
    - name: installing pip
      apt:
        name: python3-pip
        state: present
    - name: installing python3-psycopg2
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - python3-psycopg2
        - postgresql-contrib

    - name: conf pg_hba.con
      replace:
        path: /etc/postgresql/10/main/pg_hba.conf
        regexp: "local  all      all          peer"
        replace: "local  all      all          md5"
      notify: restart postgres
    - name: shwitch user
      command: psql
      become: yes
      become_user: postgres
    - name: connecting to db and update password for db user
      postgresql_user:
        #db: "{{db}}"
        name: "{{user2}}"
        password: "{{passwd}}"

    - name: creating db
      postgresql_user:
        name: "{{dbname}}"
    - name: GRANT ALL PRIVILEGES ON DATABASE
      postgresql_privs:
        db: "{{dbname}}"
        privs: "{{permission}}"
        type: "{{typ}}"
        role: "{{user2}}"
    - name: Exit from the psql shell
      command: "{{item}}"
      loop:
        - \q
        - exit

  
...


