# database configuration, creating user for db, creating db
    - name: creating user
      become: true
      user:
        name: "{{user2}}"
        comment: "{{comment}}"
    - name: installing pip
      apt:
        name: python3-pip
        state: present
    - name: installing python3-psycopg2
      pip:
        name: psycopg2-binary
        state: present
    - name: connecting to db and update password for db user
      postgresql_user:
        db: "{{db}}"
        name: "{{user2}}"
        password: "{{passwd}}"
      become_exe: "{{username}}"
      become_pass: "{{pass}}"
    - name: creating db
      postgresql_user:
        name: "{{dbname}}"
    - name: GRANT ALL PRIVILEGES ON DATABASE
      postgresql_privs:
        db: "{{dbname}}"
        privs: "{{permission}}"
        type: "{{typ}}"
        role: "{{user2}}"
    - name: Exit from the psql shell
      command: "{{item}}"
      loop:
        - \q
        - exit
...


