---
   - name: include variale
     include:
       - vars_files: "{{file}}"
   - name: ensure the password for the default PostgreSQL user is changed
     user:
        name: "{{user_name}}"
        update_password: always
        password: "{{ password | password_hash('sha512')}}"
        #become: yes
        #become_user: "{{user_name}}"

   - name: creating user for database
     become: yes
     become_user: "{{user_name}}"
     postgresql_user:
        db: "{{db1}}"
        name: "{{db_user}}"
        password: "{{db_user}}"

   - name: creating db
     postgresql_db:
        name: "{{db2}}"
        owner: "{{db_user}}"

   - name: grant priv to "{{}}"
     postgresql_privs:
        database: "{{db2}}"
        privs: ALL
        type: database
        role: "{{db_user}}"
#  become: yes
#  become_method: su
#  become_user: "{{user_name}}"
...