---
   - name: ensure the password for the default PostgreSQL user is changed
     user:
        name: "{{user_name}}"
        update_password: always
        password: "{{ password | password_hash('sha512')}}"

   - name: creating user for database
     become: yes
     become_user: postgres
     postgresql_user:
        name: "{{db_user}}"
        password: "{{db_user}}"

   - name: creating db
     postgresql_db:
        name: "{{db2}}"
        owner: "{{db_user}}"

   - name: grant priv to "{{}}"
     postgresql_privs:
        database: "{{db2}}"
        privs: ALL
        type: database
        role: "{{db_user}}"

...