---
# tasks file for sonarqube
- name: configure sonar-server
  hosts: sonar
  become: yes
  roles:
    include: "{{item}}"
  with_items:
    - vm.max_map_count.yml
    - openjdk.yml
    - add_postgres_repo.yml
    - install_postgres.yml
    - maange_postgres_user.yml
    - Download_Install_ SonarQube.yml
    - sonar_user_conf.yml
    - sonar_properties.yml
    - Configure_Systemd_service.yml