---
# tasks file for
- name: configuration of SonarQube
  include: "{{ item }}"
  with_items:
    - limits_conf_and_packages.yml
    - Setup_PostgreSQL_Database
    - postgres_user_and_db_user_mngmnt.yml
    - Download_and_Install_SonarQube
    - Create_Group_and_User.yml
    - post_steps_of_sonarqube.yml
    - Configure_Systemd_service.yml