---

# tasks file for sonarqube
- name: configuring sonarqube server
  include: "{{item}}"
  with_items:
    - limits_conf.yml
    - java_config.yml
    - postgress.yml
    - startpsql.yml
    - loginTocreatedb.yml
    - sonarqube.yml
    - sonar_conf.yml
    - startsonarqube_service.yml
...
