---
- name: Change the password for the default PostgreSQL user.
  user:
   name: "{{ user }}"
   password: "{{ pass }}"
- block:
    - name: adding new db user
      postgresql_user:
          name: "{{ db_user }}"
          password: "{{ pass1 }}"
          state: present
    - name: creating database
      postgresql_db:
        name: "{{ db }}"
        owner: sonar
        state: present
    - name: provide prvilleges
      postgresql_privs:
        db: "{{ db }}"
        privs: ALL
        type: database
        role: "{{ db_user }}"
  become: true
  become_user: postgres