---
- name: Change the password for the default PostgreSQL user.
  user: "{{ user }}"
  password: "{{ psswd }}"
- name: creating data base
  postgresql_db:
    name: "{{ db }}"
    state: present
- name: adding new db user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ passwd1 }}"
- name: provide prvilleges to {name}
  postgresql_privs:
    db: "{{ db }}"
    privs: ALL
    type: database
    role: "{{ db_user }}"