---
- name: apt-get update
  apt:
    update_cache: yes
#- name: Adding the PostgreSQL Repo
#  apt_repository:
#    repo: "{{ url }}"
#    state: present
#
#- name: adding key
#  apt_key:
#    url: "{{ key_url }}"
#    state: present

- name: installing  PostgreSQL packages
  package:
    name: "{{ packages }}"
    state: present
- name: installing psycopg2
  pip:
    name: "{{pip_package}}"
    state: present
- name: version of postgres
  command: "{{ cmd1 }}"
  register: version

- name: print psql version
  debug:
    var: version

- name: Start PostgreSQL Database server
  systemd:
    name: "{{ service }}"
    state: started
    enabled: yes
  register: status
- name: postgres status
  debug:
    var: status