---
- block:
    - name: adding user to sonar-proprties
      replace:
        dest: "{{path}}"
        regexp: "{{find}}"
        replace: "{{replace}}"
      with_items:
        - {path: "{{path1}}", find: "{{find1}}", replace: "{{replace1}}"}
        - {path: "{{path2}}", find: "{{find2}}", replace: "{{replace2}}"}

    - name: switch user to sonar and run sonar.sh
      shell: "{{script}}"
      args:
        chdir: "{{dir}}"
      register: output
    - name: status of sonar service
      debug:
        var: output
  become: yes
  become_user: "{{sonarqube_user}}"