---

- name: adding {{ group_name }} group
  group:
    name: "{{group_name}}"
    state: present
- name: adduser for sonarqube
  user:
    name: "{{sonarqube_user}}"
    comment: "{{comment}}"
    group: "{{group_name}}"
    createhome: yes
    password: "{{sonarqube_password | password_hash ('sha512')}}"

#- name: Change file ownership, group and permissions
#  file:
#    path: "{{des1}}"
#    owner: "{{sonarqube_user}}"
#    group: "{{group_name}}"
#    mode: 0757
#    recurse: yes
#    state: directory