---
- block:
    - name: adding user to sonar.proprties
      replace:
        path: "{{item_path}}"
        regexp: "{{item_find}}"
        replace: "{{item_replace}}"
      loop_var:
        - {path: "{{path1}}", find: "{{find_text}}", replace: "{{replace_text}}"}
        - {path: "{{path2}}", find: "{{find_text1}}", replace: "{{replace_text1}}"}


    - name: switch user to sonar and run sonar.sh
      shell: "{{script}}"
      args:
        chdir: "{{dir}}"
      register: output
    - name: status of sonar service
      debug:
        var: output
  become: yes
  become_user: "{{sonarqube_user}"