---
- block:
    - name: adding user to sonar.proprties
      replace:
        path: "{{line_path}}"
        regexp: "{{line_find}}"
        replace: "{{line_replace}}"
      with_items: "{{line_list}}"
      loop_control:
        loop_var:
        - {path: "{{path1}}", find: "{{find_text}}", replace: "{{replace_text}}"}
        - {path: "{{path2}}", find: "{{find_text1}}", replace: "{{replace_text1}}"}


    - name: switch user to sonar and run sonar.sh
      shell: "{{script}}"
      args:
        chdir: "{{dir}}"
      register: output
    - name: status of sonar service
      debug:
        var: output
  become: yes
  become_user: "{{sonarqube_user}}"