---
# handlers file for sonarqube
- name: deamon reload
  systemd:
   daemon_reload: yes
   name: sonar
   state: started
   enabled: yes
  register: status
- name: print status
  debug:
    var: status