---
# tasks file for packages.
- name: installing jdk, maven, git,
  apt:
    name: "{{name1}}"
    state: "{{state1}}"
    update_cache: "{{update}}"
- name: adding jenkins.io.key
  apt_key:
    url: "{{url}}"
    state: "{{state1}}"
- name: adding package into sources.list
  apt_repository:
    repo: "{{repo}}"

