---
# tasks file for packages.
- name: installing jdk, maven, git,
  apt:
<<<<<<< HEAD
    name: "{{item.name1}}"
    state: "{{item.state}}"
    update_cache: "{{item.update}}"
  loop:
    - "{{name1}}"
    - "{{state}}"
    - "{{update}}"
=======
    name: "{{name1}}"
    state: "{{state1}}"
    update_cache: "{{update}}"
>>>>>>> ed872980071af50f118eeaef90ca5f0d0ae22a92
- name: adding jenkins.io.key
  apt_key:
    url: "{{url}}"
    state: "{{state1}}"
  loop:
    - "{{url}}"
    - "{{state}}"
- name: adding package into sources.list
  apt_repository:
    repo: "{{repo}}"
  loop:
    -  "{{repo}}"


