---
- name: login to docker hub
  docker_login:
    username: "92840"
    password: "London@123"
- name: remove if { name } image is exists
  docker_image:
    name: "{{ remove_image }}"
    tag: "{{ image_tag }}"
    state: absent
  ignore_errors: yes

- name: Bulding image
  docker_image:
    path: "{{ dockerfile_path }}"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"

- name: Tag image and push to Repo
  docker_image:
    name: "{{ image }}"
    repository: "{{ repo }}"
    push: yes

