- name: stop and remove if { name } container is running
  docker_container:
    name: "{{ item.container_name}}"
    state: "{{ item.container_state }}"
  with_items:
    - { container_name: "{{cn}}", container_state: "{{cs}}" }
    - { container_name: "{{cn1}}", container_state: "{{cs1}}" }
  ignore_errors: yes

- name: login to docker hub
  docker_login:
    username: "92840"
    password: "London@123"

- name: delete old builds
  docker_image:
    name: "{{ remove_image }}"
    tag: "{{ image_tag }}"
    state: absent
  ignore_errors: yes

- name: Bulding image
  docker_image:
    path: "{{ dockerfile_path }}"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"

#- name: Tag image and push to Repo
#  docker_image:
#    name: "{{ image }}"
#    repository: "{{ repo }}"
#    push: yes

- name: creating { name }containers
  docker_container:
    name: "{{ cn }}"
    image: "{{ image_to_run }}"
    state: started
    ports:
      - "8080:8080"
