#- name: stop and remove if { name } container is running
#  docker_container:
#    name: "{{ item.container_name}}"
#    state: "{{ item.container_state }}"
#  with_items:
#    - { container_name: "{{cn}}", container_state: "{{cs}}" }
#    - { container_name: "{{cn1}}", container_state: "{{cs1}}" }
#  ignore_errors: yes

- name: login to docker hub
  docker_login:
    username: "92840"
    password: "London@123"

- name: delete old builds
  docker_image:
    name: "{{ item.remove_image }}"
    tag: "{{ item.image_tag }}"
    state: absent
  with_items:
    - {remove_image: "{{image1}}", image_tag: "{{tag}}"}
    - {remove_image: "{{image2}}", image_tag: "{{tag}}"}
  ignore_errors: yes

- name: Bulding new image
  docker_image:
    path: "{{ dockerfile_path }}"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"

- name: Tag image and push to Repo
  docker_image:
    name: "{{ image }}"
    repository: "{{ repo }}"
    push: yes


