---
# copy limit.conf file to remote
src: limits.conf
path: /etc/security/limits.conf

# java configuration and zip
pre_packages:
  - unzip
  - openjdk-11-jdk
  - openjdk-11-jre
notify1: java version
cmd: java -version
register_var: version

# postgres configuration
postgres_repo: "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main"
Key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_packages:
  - postgresql
  - postgresql-contrib
postgresql_python_library: psycopg2-binary

# manage postgres service
notify_1: start and enable postgres
service_1: postgresql
user_name: postgres
password: postgres_pass.yml
password1: postgres_pass.yml
db1: psql
db_user: sonar
db2: sonarqube

# sonarqube configuration
sonar_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip"
des: /opt/sonarqube-7.9.1.zip
des1: /opt/sonarqube-7.9.1
group_name: sonar
sonarqube_user: sonar
comment: user to run SonarQube
path1: /opt/sonarqube-7.9.1/conf/sonar.properties
#find1:
#  - "#sonar.jdbc.username=, #sonar.jdbc.password="
block: |
  sonar.jdbc.username=sonar
  sonar.jdbc.password=sonar

path2: /opt/sonarqube-7.9.1/bin/linux-x86-64/sonar.sh
find2: "^RUN_AS_USER="
insert: "^#RUN_AS_USER="
replace2: RUN_AS_USER=sonar
script: ./sonar.sh start >> sonarlog.txt
dir: /opt/sonarqube-7.9.1/bin/linux-x86-64/



