---
# vars file for sonarqube
path: /etc/security/limits.conf
block1: "sonarqube - nofile - 65536"
block2: "sonarqube - nproc - 4096"
pkg1: unzip
pkg2: openjdk-11-jdk
cmd: java -version

# postgreSql configuration.

repo: " deb http://apt.postgresql.org/pub/repos/apt/dists/bionic-pgdg/11/binary-arm64/Packages.gz "
apt_key: https://www.postgresql.org/media/keys/ACCC4CF8.asc
pkg3: postgresql
pkg4: postgresql-contrib
service1: postgresql
service_status: started
username: postgres
pass: "postgres"

# database user management
user1: postgres
user2: sonar
comment: database user
db: psql
passwd: "sonar"
dbname: sonarqube
permission: ALL
typ: database

# sonarqube conf
src: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.4.zip"
dest: /opt/sonarqube
group_name: sonar
comnt: user for sonar server
mode: 667

#configure sonar.properties
path1: /opt/sonarqube/conf/sonar.properties
user: "#sonar.jdbc.username="
add_user: "sonar.jdbc.username=sonar"
default_passwd: "#sonar.jdbc.password="
add_passwd: "sonar.jdbc.password=sonar"
#sonar.sh config
path2: /opt/sonarqube/bin/linux-x86-64/sonar.sh
RUN_AS_USER: "#RUN_AS_USER="
rpl: "RUN_AS_USER=sonar"

#starting sonarqube service
script: sonar.sh start
script_path: /opt/sonarqube/bin/linux-x86-64/