---
# copy limit.conf file to remote
src: limits.conf
path: /etc/security/limits.conf

# java configuration and zip
pre_packages:
  - unzip
  - openjdk-11-jdk
  - openjdk-11-jre
notify1: java version
cmd: java -version
register_var: version

# postgres configuration
postgres_repo: "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main"
Key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_packages:
  - postgresql
  - postgresql-contrib
postgresql_python_library: python-psycopg2

# manage postgres service
notify_1: start and enable postgres
service_1: postgresql
user_name: postgres
password: postgres_pass.yml
db1: psql
db_user: sonar
db2: sonarqube

# sonarqube configuration
src1: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip"
des: /opt/sonarqube/
group_name: sonar
sonarqube_user: sonar
comment: user to run SonarQube
path1: /opt/sonarqube/conf/sonar.properties
find_text:
  - "#sonar.jdbc.username="
  - "#sonar.jdbc.password="
replace_text:
  - sonar.jdbc.username=sonar
  - sonar.jdbc.password=sonar
path2: /opt/sonarqube/bin/linux-x86-64/sonar.sh
find_text1: "#RUN_AS_USER"
replace_text1: RUN_AS_USER=sonar
script: ./sonar.sh start
script2: ./sonar.sh status
dir: /opt/sonarqube/bin/linux-x86-64/



